### ISSUE TITLE
2018.03.19 日志处理中，win7作为网盘挂载，容易掉

### ISSUE THREAD

**Issue by HeathKang** [Mabo-IoT/work-issues#1]
解决挂载不稳定问题

**Comment by HeathKang** [comment]
## 猜测1
win 7 睡眠问题（待验证）

## 解决
- linux写一个监测脚本，固定时间间隔监测是否挂载成功，如掉线，自动重新挂载，并进行日志记录

**Comment by YHYJ** [comment]
1.win7睡眠/休眠会导致主动停止网络连接，挂载失败，禁止win7睡眠/休眠即可

**Comment by HeathKang** [comment]
## 监测脚本大致思路：
1. 每隔1min(可配置)监测网盘是否挂载上；
2. 如断掉，自动重新挂载， 并检测是否挂载成功；
3. 若无法挂载成功，则ping 网盘PC，如ping通，则报log：检查PC网盘设置；如ping不通，报log：网络问题或PC关闭；

**Comment by YHYJ** [comment]
1.完成
2.完成
3.ping不通会导致脚本出现BUG

**Comment by YHYJ** [comment]
已完成
